### ISSUE TITLE
[Feature Request] Configurable Farm damage

### ISSUE THREAD

**Issue by happybandit360** [davidmaamoaix/TinyMobFarm#9]
I'm am working with a group building a 1.12.2 modpack and there are some features we would love to see added to your mob if it is possible.

1) A config setting to change how much damage each farm does to the durability of the lasso. Alternatively, being able to config the chance of damage from a farm. This way we could allow a passive-only farm to run longer than an aggressive mob farm.

2) Farms automatically disable if there is no valid inventory space (either no chest present or a full chest). This would be to prevent items from falling into the world and potentially causing lag.

3) The ability to add or remove items to a mob's loot table would be amazing, but it's understandable if that is not possible.

**Comment by linxuanm** [comment]
Sorry for the very late reply.

1. I thought I already added that but apparently I didn't. Sorry for the inconvenience.
2. I have mixed thoughts on this. Organizing the storage to prevent drops from spitting out was an intended challenge to the player, and the player was meant to control the mob farm via redstone. However, due to how numerous people requested this feature, I am considering adding a config option to disable spitting out the drops.

**Comment by JoelZBub** [comment]
A config option for number 2 would be very useful to server admins trying to maintain a smooth running server despite those players that view challenges presented to them in the game as a waste of their own personal time at the expense of server performance and others' play quality. 😁

**Comment by JoelZBub** [comment]
Regarding number 3:
It's not so much about adding drops to loot tables as it is being able to add drops to entities that don't use loot tables. For instance, mob from The Erebus have their drops hardcoded, and drop nothing in a Tiny Mob Farm. 
It would be a useful feature for pack builders to have a config option that included, for example: `[<modid:entity>, <modid:itemStack1>,<weight1>,<modid:itemStack2>,<weight2>...<minTicksBetweenDrops>, <maxTicksBetweenDrops>]`

**Comment by linxuanm** [comment]
I see your concern also about mods whose entities have hard-coded drops instead of loot tables. Fortunately, mod pack makers can utilize mods such as CraftTweaker (or was it one of CraftTweaker's addon that changes loot table?) to edit the loot table, and the changes will reflect on Tiny Mob Farm's drop.

Alternatively, I might add a config for tweaking loot drops in the future, but it is rather low on my TODO list now, as my priority is on updating this mod to 1.14.4 and adapting other new features suggested earlier. Sorry for any inconvenience.
